---
# Docker compose file for the purpose of building images
version: "3.8"
services:
  scratch:
    build:
      dockerfile: .aws/scratch.Dockerfile
      context: ../
      args:
        ARCH: "${ARCH}"
        DATE: ${DATE}
        VERSION: 0.9.0
        TARGETARCH: ${ARCH}
    image: ${REGISTRY_URI}nginx/nginx-prometheus-exporter:${TAG}-${ARCH:-amd64}

  amzn2:
    build:
      dockerfile: .aws/amzn2.Dockerfile
      context: ../
      args:
        ARCH: "${ARCH}"
        BASE_IMAGE: public.ecr.aws/amazonlinux/amazonlinux:2.0.20210721.2
        DATE: ${DATE}
        VERSION: 0.9.0
        TARGETARCH: ${ARCH}
    image: ${REGISTRY_URI}nginx-prometheus-exporter:${TAG}-${ARCH:-amd64}
